### ISSUE TITLE
create_recording doesn't use Voctoweb.Path

### ISSUE THREAD

**Issue by lukas2511** [voc/voctopublish#71] opened 2019-03-19 23:26 UTC
In some cases uploaded files and paths in Voctoweb may differ after publishing a recording.

For creating recordings on the voctoweb API the `MirrorFolder` property together with a pre-defined prefix (seemingly the contributors main directory) is used.

For actually uploading the video `Voctoweb.Path` property is used as a prefix.

For the latest openchaos upload this resulted in the year subdirectory missing in the recordings path, even though it was specified in Voctoweb.Path and files have actually been uploaded to the correct directory.

**Comment by Florob** [comment] 2019-03-20 00:46
Duplicate of #27

**Closed by Florob** 2019-03-20 00:46 UTC

**Comment by derpeter** [comment] 2019-03-20 16:35
actually this is not a bug. As the PATH we give to the API when creating an recording is absolute to the path of the conference the recording belongs to.
